{{- if .Values.client.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "launchpad.fullname" . }}-client
  labels:
    {{- include "launchpad.client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "launchpad.client.selectorLabels" . | nindent 4 }}
{{- end }}
